//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacaoTesteUnibratec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cardapio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cardapio()
        {
            this.ItemCardapio = new HashSet<ItemCardapio>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public string Observacao { get; set; }
        public int IdFoodTruck { get; set; }
    
        public virtual FoodTruck FoodTruck { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemCardapio> ItemCardapio { get; set; }
    }
}
