//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacaoTesteUnibratec
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodTruckFuncionario
    {
        public int Id { get; set; }
        public int IdFoodTruck { get; set; }
        public int IdFuncionario { get; set; }
    
        public virtual FoodTruck FoodTruck { get; set; }
        public virtual Funcionario Funcionario { get; set; }
    }
}
