//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacaoTesteUnibratec
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodTruck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodTruck()
        {
            this.AvaliacaoFoodTruck = new HashSet<AvaliacaoFoodTruck>();
            this.Cardapio = new HashSet<Cardapio>();
            this.FoodTruckFuncionario = new HashSet<FoodTruckFuncionario>();
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CNPJ { get; set; }
        public string Especialidade { get; set; }
        public string RazaoSocial { get; set; }
        public string Telefone { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Foto { get; set; }
        public string Estado { get; set; }
        public string Cidade { get; set; }
        public string Bairro { get; set; }
        public string Rua { get; set; }
        public string Numero { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }

        public string EmailFuncionario { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacaoFoodTruck> AvaliacaoFoodTruck { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cardapio> Cardapio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodTruckFuncionario> FoodTruckFuncionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
